#!/bin/sh

if [[ "$(pwd)" != "$HOME"* ]]; then 
  echo This script must be run in a codebase located within the $HOME folder. Please re-clone this repository and try again
fi

docker-compose build &&\
docker-compose run web npm install &&\
docker-compose up
