#!/bin/sh

export NODEMON_OPTS=""
export WEBPACK_DEV_OPTS=""

if [[ "$(pwd)" != "$HOME"* ]]; then 
  echo This script must be run in a codebase located within the $HOME folder. Please re-clone this repository and try again
  exit 1
fi

if [ "$MSYSTEM" == "MINGW64" ]; then
  export NODEMON_OPTS="$NODEMON_OPTS --polling-interval 200"
  export WEBPACK_DEV_OPTS="$WEBPACK_DEV_OPTS --watch-poll"
fi

docker-compose build &&\
docker-compose run web npm install &&\
docker-compose up
